/**
 * Angular + Webpack 5 + CE.SDK + PDF/X-3 Integration Test
 *
 * This test verifies the full integration:
 * 1. Angular 18 + Webpack 5 project setup
 * 2. CE.SDK editor initialization
 * 3. PDF export from CE.SDK
 * 4. PDF/X-3 conversion using the plugin
 *
 * The test project is generated by scripts/create-angular-cesdk-test-project.sh
 */

import { test, expect } from '@playwright/test';
import { execSync, spawn, ChildProcess } from 'child_process';
import { existsSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';

const PLUGIN_DIR = join(__dirname, '..');
const PROJECT_DIR = join(PLUGIN_DIR, 'test', 'webpack5-angular-cesdk-project');
const SERVER_PORT = 4299;
const SERVER_URL = `http://localhost:${SERVER_PORT}`;

// Path constants for restoring original files between test suites
const ANGULAR_JSON_PATH = join(PROJECT_DIR, 'angular.json');
const WEBPACK_CONFIG_PATH = join(PROJECT_DIR, 'webpack.config.js');

// Original file contents - stored by the script that creates the project
// We read these from the generated project to restore between test runs
let ORIGINAL_ANGULAR_JSON: string | null = null;
let ORIGINAL_WEBPACK_CONFIG: string | null = null;

/**
 * Ensures the Angular project files are in their original state.
 * This is critical because other test suites modify angular.json and webpack.config.js,
 * and if a previous test run failed, the files may be left in a modified state.
 */
async function ensureOriginalProjectFiles(): Promise<void> {
  const fs = await import('fs/promises');

  // If project doesn't exist yet, nothing to restore
  if (!existsSync(PROJECT_DIR)) {
    return;
  }

  // Check if symlink to plugin ROOT exists and is valid
  // This mimics npm package structure: node_modules/@imgly/plugin-print-ready-pdfs-web/dist/
  const pluginSymlinkPath = join(PROJECT_DIR, 'node_modules', '@imgly', 'plugin-print-ready-pdfs-web');

  try {
    // Check if symlink exists and points to a valid target
    const symlinkTarget = await fs.realpath(pluginSymlinkPath);
    const expectedTarget = await fs.realpath(PLUGIN_DIR);
    if (symlinkTarget !== expectedTarget) {
      throw new Error('Symlink points to wrong target');
    }
    // Check if target has required files in dist/ subdirectory (like npm package)
    if (!existsSync(join(symlinkTarget, 'dist', 'gs.js'))) {
      throw new Error('gs.js not found in symlink target dist/');
    }
  } catch (error) {
    // Symlink is broken or missing - recreate it
    console.log('Recreating plugin symlink to plugin root...');
    const imglyDir = join(PROJECT_DIR, 'node_modules', '@imgly');
    if (!existsSync(imglyDir)) {
      await fs.mkdir(imglyDir, { recursive: true });
    }
    try {
      await fs.unlink(pluginSymlinkPath);
    } catch {
      // Symlink didn't exist
    }
    // Symlink to plugin ROOT, not dist - to match npm package structure
    await fs.symlink(PLUGIN_DIR, pluginSymlinkPath);
  }

  // Read current files to check if they need restoration
  const currentAngularJson = await fs.readFile(ANGULAR_JSON_PATH, 'utf-8');
  const currentWebpackConfig = await fs.readFile(WEBPACK_CONFIG_PATH, 'utf-8');

  // Check if angular.json has the original asset configuration
  // The original config has input: "node_modules/@imgly/plugin-print-ready-pdfs-web/dist"
  // and output: "/assets/print-ready-pdfs"
  const angularJson = JSON.parse(currentAngularJson);
  const buildOptions = angularJson.projects?.['webpack5-angular-cesdk-project']?.architect?.build?.options;

  if (buildOptions) {
    const hasOriginalAssetConfig = buildOptions.assets?.some((asset: any) => {
      return typeof asset === 'object' &&
             asset.input?.includes('plugin-print-ready-pdfs-web/dist') &&
             asset.output === '/assets/print-ready-pdfs';
    });

    // Check if webpack.config.js has copy-webpack-plugin (which it shouldn't in original)
    const hasCopyPlugin = currentWebpackConfig.includes('copy-webpack-plugin');

    if (!hasOriginalAssetConfig || hasCopyPlugin) {
      console.log('Detected modified project files from previous test run, recreating project...');
      // Remove and recreate the project to get a clean state
      rmSync(PROJECT_DIR, { recursive: true, force: true });
    }
  }
}

test.describe('Angular + Webpack 5 + CE.SDK + PDF/X-3 Integration', () => {
  let serverProcess: ChildProcess | null = null;

  test.beforeAll(async () => {
    // Ensure project files are in original state (handles leftover state from failed tests)
    await ensureOriginalProjectFiles();

    // Ensure plugin is built
    if (!existsSync(join(PLUGIN_DIR, 'dist', 'index.mjs'))) {
      console.log('Building plugin...');
      execSync('pnpm run build', { cwd: PLUGIN_DIR, stdio: 'inherit' });
    }

    // Create project if it doesn't exist
    if (!existsSync(PROJECT_DIR)) {
      console.log('Creating Angular test project...');
      execSync('bash scripts/create-angular-cesdk-test-project.sh', {
        cwd: PLUGIN_DIR,
        stdio: 'inherit'
      });
    }

    // Store original file contents for other test suites to restore
    const fs = await import('fs/promises');
    ORIGINAL_ANGULAR_JSON = await fs.readFile(ANGULAR_JSON_PATH, 'utf-8');
    ORIGINAL_WEBPACK_CONFIG = await fs.readFile(WEBPACK_CONFIG_PATH, 'utf-8');

    // Build Angular project
    console.log('Building Angular project...');
    try {
      execSync('npm run build', {
        cwd: PROJECT_DIR,
        stdio: 'inherit',
        timeout: 300000 // 5 minutes
      });
    } catch (error) {
      console.error('Angular build failed:', error);
      throw error;
    }

    // Start HTTP server
    console.log(`Starting HTTP server on port ${SERVER_PORT}...`);
    serverProcess = spawn('npm', ['run', 'serve'], {
      cwd: PROJECT_DIR,
      stdio: 'pipe',
      detached: false
    });

    // Wait for server to start
    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => {
        reject(new Error('Server startup timeout'));
      }, 30000);

      serverProcess!.stdout?.on('data', (data) => {
        const output = data.toString();
        console.log('[Server]', output);
        if (output.includes('Available on') || output.includes('Serving')) {
          clearTimeout(timeout);
          // Give it a moment to fully start
          setTimeout(resolve, 1000);
        }
      });

      serverProcess!.stderr?.on('data', (data) => {
        console.error('[Server Error]', data.toString());
      });

      serverProcess!.on('error', (error) => {
        clearTimeout(timeout);
        reject(error);
      });
    });
  });

  test.afterAll(async () => {
    // Kill server
    if (serverProcess) {
      console.log('Stopping server...');
      serverProcess.kill('SIGTERM');
      serverProcess = null;
    }
  });

  test('should load CE.SDK and convert PDF to PDF/X-3 without file:// errors', async ({ page }) => {
    const consoleMessages: string[] = [];
    const errors: string[] = [];

    // Capture console messages
    page.on('console', (msg) => {
      const text = msg.text();
      consoleMessages.push(`[${msg.type()}] ${text}`);
      if (msg.type() === 'error') {
        errors.push(text);
      }
    });

    // Capture page errors
    page.on('pageerror', (error) => {
      errors.push(`Page error: ${error.message}`);
    });

    // Navigate to the app
    console.log(`Navigating to ${SERVER_URL}...`);
    await page.goto(SERVER_URL, { timeout: 60000 });

    // Wait for initial load
    await page.waitForLoadState('networkidle');

    // Wait for plugin import to succeed
    console.log('Waiting for plugin import...');
    await page.waitForFunction(
      () => (window as any).testResults?.importSuccess === true,
      { timeout: 30000 }
    );

    // Verify no file:// protocol errors during import
    const fileProtocolErrors = errors.filter(
      (e) => e.includes('file://') || e.includes('Cannot find module')
    );
    expect(fileProtocolErrors).toHaveLength(0);

    // Wait for CE.SDK to initialize
    console.log('Waiting for CE.SDK initialization...');
    await page.waitForFunction(
      () => (window as any).testResults?.cesdkReady === true,
      { timeout: 120000 } // CE.SDK can take a while to load
    );

    // Verify CE.SDK loaded without errors
    const cesdkErrors = errors.filter(
      (e) => e.toLowerCase().includes('cesdk') || e.toLowerCase().includes('creative')
    );
    // Some warnings are OK, but no critical errors
    const criticalCesdkErrors = cesdkErrors.filter(
      (e) => !e.includes('Warning') && !e.includes('deprecated')
    );
    expect(criticalCesdkErrors).toHaveLength(0);

    // Trigger PDF export and conversion
    console.log('Triggering PDF export and PDF/X-3 conversion...');
    await page.evaluate(() => {
      return (window as any).triggerExport();
    });

    // Wait for conversion to complete
    console.log('Waiting for conversion to complete...');
    await page.waitForFunction(
      () => (window as any).testResults?.testComplete === true,
      { timeout: 120000 } // Conversion can take time
    );

    // Get final results
    const results = await page.evaluate(() => (window as any).testResults);
    console.log('Test results:', JSON.stringify(results, null, 2));

    // Verify conversion success
    expect(results.importSuccess).toBe(true);
    expect(results.cesdkReady).toBe(true);
    expect(results.conversionAttempted).toBe(true);
    expect(results.conversionSuccess).toBe(true);
    expect(results.conversionError).toBeNull();
    expect(results.pdfSize).toBeGreaterThan(0);

    // Check for file:// errors during entire test
    const allFileErrors = consoleMessages.filter(
      (m) => m.includes('file://') && m.includes('error')
    );
    expect(allFileErrors).toHaveLength(0);

    console.log('Test passed! PDF/X-3 conversion successful.');
    console.log(`Output PDF size: ${results.pdfSize} bytes`);
  });

  test('should handle multiple export profiles', async ({ page }) => {
    const profiles = ['fogra39', 'gracol', 'srgb'];

    await page.goto(SERVER_URL, { timeout: 60000 });
    await page.waitForLoadState('networkidle');

    // Wait for CE.SDK
    await page.waitForFunction(
      () => (window as any).testResults?.cesdkReady === true,
      { timeout: 120000 }
    );

    for (const profile of profiles) {
      console.log(`Testing profile: ${profile}`);

      // Reset test results
      await page.evaluate(() => {
        (window as any).testResults.conversionAttempted = false;
        (window as any).testResults.conversionSuccess = false;
        (window as any).testResults.conversionError = null;
        (window as any).testResults.pdfSize = null;
        (window as any).testResults.testComplete = false;
      });

      // Select profile
      await page.selectOption('select', profile);

      // Trigger export
      await page.evaluate(() => (window as any).triggerExport());

      // Wait for completion
      await page.waitForFunction(
        () => (window as any).testResults?.testComplete === true,
        { timeout: 120000 }
      );

      // Verify success
      const results = await page.evaluate(() => (window as any).testResults);
      expect(results.conversionSuccess).toBe(true);
      expect(results.pdfSize).toBeGreaterThan(0);

      console.log(`Profile ${profile}: Success (${results.pdfSize} bytes)`);
    }
  });

  test('should show helpful error message when assets are not found', async ({ page }) => {
    // Navigate with testError=true to skip assetPath and trigger the error
    console.log('Testing error message when assets are not discoverable...');
    await page.goto(`${SERVER_URL}/?testError=true`, { timeout: 60000 });
    await page.waitForLoadState('networkidle');

    // Wait for CE.SDK
    await page.waitForFunction(
      () => (window as any).testResults?.cesdkReady === true,
      { timeout: 120000 }
    );

    // Trigger export (should fail with helpful error)
    await page.evaluate(() => (window as any).triggerExport());

    // Wait for completion
    await page.waitForFunction(
      () => (window as any).testResults?.testComplete === true,
      { timeout: 120000 }
    );

    // Get results
    const results = await page.evaluate(() => (window as any).testResults);

    // Verify conversion failed
    expect(results.conversionSuccess).toBe(false);
    expect(results.conversionError).not.toBeNull();

    // Verify error message contains helpful information
    const errorMessage = results.conversionError as string;
    expect(errorMessage).toContain('Could not locate plugin assets');
    expect(errorMessage).toContain('assetPath option is required');
    expect(errorMessage).toContain('Angular CLI');
    expect(errorMessage).toContain('cp node_modules/@imgly/plugin-print-ready-pdfs-web/dist/');
    expect(errorMessage).toContain('https://img.ly/docs/cesdk/print-ready-pdfs/bundler-setup');

    console.log('Error message test passed - helpful error shown to user');
  });
});

/**
 * Test that verifies the Angular CLI assets configuration from the error message works.
 * This simulates the real user experience:
 * 1. First attempt WITHOUT assets configured → should fail with helpful error
 * 2. Update angular.json with the recommended assets configuration
 * 3. Rebuild and verify it works
 *
 * This test reuses the existing Angular project but modifies angular.json dynamically.
 */
test.describe('Angular CLI Assets Configuration from Error Message', () => {
  let serverProcess: ChildProcess | null = null;
  const ASSETS_TEST_PORT = 4298;
  let originalAngularJson: string;

  test.beforeAll(async () => {
    // Ensure plugin is built
    if (!existsSync(join(PLUGIN_DIR, 'dist', 'index.mjs'))) {
      console.log('Building plugin...');
      execSync('pnpm run build', { cwd: PLUGIN_DIR, stdio: 'inherit' });
    }

    // Create project if it doesn't exist
    if (!existsSync(PROJECT_DIR)) {
      console.log('Creating Angular test project...');
      execSync('bash scripts/create-angular-cesdk-test-project.sh', {
        cwd: PLUGIN_DIR,
        stdio: 'inherit'
      });
    }

    // Use the shared original or read from file
    const fs = await import('fs/promises');
    if (ORIGINAL_ANGULAR_JSON) {
      originalAngularJson = ORIGINAL_ANGULAR_JSON;
      // Restore to original state in case a previous test left it modified
      await fs.writeFile(ANGULAR_JSON_PATH, originalAngularJson);
    } else {
      originalAngularJson = await fs.readFile(ANGULAR_JSON_PATH, 'utf-8');
    }
  });

  test.afterAll(async () => {
    // Restore original angular.json
    if (originalAngularJson) {
      const fs = await import('fs/promises');
      await fs.writeFile(ANGULAR_JSON_PATH, originalAngularJson);
    }

    // Kill server if running
    if (serverProcess) {
      console.log('Stopping assets test server...');
      serverProcess.kill('SIGTERM');
      serverProcess = null;
    }
  });

  test('should fail without assets, then succeed after adding angular.json assets config', async ({ page }) => {
    const fs = await import('fs/promises');

    // ============================================
    // STEP 1: Build WITHOUT assets - should fail with helpful error
    // ============================================
    console.log('Step 1: Building Angular project WITHOUT assets configured...');

    // Modify angular.json to remove ALL asset configurations for our plugin
    const angularJson = JSON.parse(originalAngularJson);
    const buildOptions = angularJson.projects['webpack5-angular-cesdk-project'].architect.build.options;

    // Remove any existing plugin asset configurations
    buildOptions.assets = buildOptions.assets.filter((asset: any) => {
      if (typeof asset === 'string') return true;
      return !asset.input?.includes('plugin-print-ready-pdfs-web');
    });

    await fs.writeFile(ANGULAR_JSON_PATH, JSON.stringify(angularJson, null, 2));

    // Build Angular project without assets
    console.log('Building Angular project (no plugin assets)...');
    execSync('npm run build', { cwd: PROJECT_DIR, stdio: 'inherit', timeout: 300000 });

    // Start server
    console.log(`Starting HTTP server on port ${ASSETS_TEST_PORT}...`);
    serverProcess = spawn('npx', ['http-server', 'dist/webpack5-angular-cesdk-project', '-p', String(ASSETS_TEST_PORT), '--cors', '-c-1'], {
      cwd: PROJECT_DIR,
      stdio: 'pipe',
      detached: false
    });

    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Server startup timeout')), 30000);
      serverProcess!.stdout?.on('data', (data) => {
        const output = data.toString();
        console.log('[Assets Test Server]', output);
        if (output.includes('Available on') || output.includes('Serving')) {
          clearTimeout(timeout);
          setTimeout(resolve, 1000);
        }
      });
      serverProcess!.stderr?.on('data', (data) => console.error('[Assets Test Server Error]', data.toString()));
      serverProcess!.on('error', (error) => { clearTimeout(timeout); reject(error); });
    });

    // Navigate with testError=true (no assetPath provided)
    console.log('Testing conversion without assets (should fail)...');
    await page.goto(`http://localhost:${ASSETS_TEST_PORT}/?testError=true`, { timeout: 60000 });
    await page.waitForLoadState('networkidle');

    // Wait for CE.SDK
    await page.waitForFunction(
      () => (window as any).testResults?.cesdkReady === true,
      { timeout: 120000 }
    );

    // Trigger export (should fail)
    await page.evaluate(() => (window as any).triggerExport());
    await page.waitForFunction(
      () => (window as any).testResults?.testComplete === true,
      { timeout: 120000 }
    );

    let results = await page.evaluate(() => (window as any).testResults);
    console.log('Step 1 results:', JSON.stringify(results, null, 2));

    // Verify conversion failed with helpful error
    expect(results.conversionSuccess).toBe(false);
    expect(results.conversionError).not.toBeNull();

    const errorMessage = results.conversionError as string;
    expect(errorMessage).toContain('Could not locate plugin assets');
    expect(errorMessage).toContain('Angular CLI');
    expect(errorMessage).toContain('angular.json');
    expect(errorMessage).toContain('assetPath');

    console.log('Step 1 passed: Got expected error with Angular CLI instructions');

    // Stop server for rebuild
    serverProcess.kill('SIGTERM');
    serverProcess = null;

    // ============================================
    // STEP 2: Add the Angular CLI assets configuration from the error message
    // ============================================
    console.log('Step 2: Adding angular.json assets configuration...');

    // This is the EXACT configuration pattern from the error message that real users would use:
    // { "glob": "{gs.js,gs.wasm,*.icc}", "input": "node_modules/@imgly/plugin-print-ready-pdfs-web/dist", "output": "/assets/" }
    //
    // For our test app, we use "/assets/print-ready-pdfs/" to match what the app expects
    // (the app component uses assetPath: '/assets/print-ready-pdfs/' in normal mode)
    const testAssetConfig = {
      glob: '{gs.js,gs.wasm,*.icc}',
      input: 'node_modules/@imgly/plugin-print-ready-pdfs-web/dist',  // Exact path users would use
      output: '/assets/print-ready-pdfs/'  // Where the Angular app expects them
    };

    buildOptions.assets.push(testAssetConfig);
    await fs.writeFile(ANGULAR_JSON_PATH, JSON.stringify(angularJson, null, 2));

    console.log('Asset config added:', JSON.stringify(testAssetConfig));

    // ============================================
    // STEP 3: Rebuild and verify it works
    // ============================================
    console.log('Step 3: Rebuilding Angular project WITH assets configured...');
    execSync('npm run build', { cwd: PROJECT_DIR, stdio: 'inherit', timeout: 300000 });

    // Verify assets were copied
    const distAssetsDir = join(PROJECT_DIR, 'dist', 'webpack5-angular-cesdk-project', 'assets', 'print-ready-pdfs');
    const expectedFiles = ['gs.js', 'gs.wasm', 'ISOcoated_v2_eci.icc', 'GRACoL2013_CRPC6.icc', 'sRGB_IEC61966-2-1.icc'];
    for (const file of expectedFiles) {
      const filePath = join(distAssetsDir, file);
      if (!existsSync(filePath)) {
        throw new Error(`Angular CLI did not copy ${file} to dist/assets/print-ready-pdfs/`);
      }
    }
    console.log('Assets copied successfully by Angular CLI to /assets/print-ready-pdfs/');

    // Start server again
    console.log(`Starting HTTP server on port ${ASSETS_TEST_PORT}...`);
    serverProcess = spawn('npx', ['http-server', 'dist/webpack5-angular-cesdk-project', '-p', String(ASSETS_TEST_PORT), '--cors', '-c-1'], {
      cwd: PROJECT_DIR,
      stdio: 'pipe',
      detached: false
    });

    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Server startup timeout')), 30000);
      serverProcess!.stdout?.on('data', (data) => {
        const output = data.toString();
        console.log('[Assets Test Server]', output);
        if (output.includes('Available on') || output.includes('Serving')) {
          clearTimeout(timeout);
          setTimeout(resolve, 1000);
        }
      });
      serverProcess!.stderr?.on('data', (data) => console.error('[Assets Test Server Error]', data.toString()));
      serverProcess!.on('error', (error) => { clearTimeout(timeout); reject(error); });
    });

    // Test with assetPath pointing to where Angular CLI copied the assets
    console.log('Testing conversion WITH assets and assetPath...');

    // Clear browser cache
    const client = await page.context().newCDPSession(page);
    await client.send('Network.clearBrowserCache');

    // Navigate normally (assets should now be available, use assetPath: '/assets/')
    await page.goto(`http://localhost:${ASSETS_TEST_PORT}/`, { timeout: 60000 });
    await page.waitForLoadState('networkidle');

    // Wait for CE.SDK
    await page.waitForFunction(
      () => (window as any).testResults?.cesdkReady === true,
      { timeout: 120000 }
    );

    // Trigger export (should succeed)
    await page.evaluate(() => (window as any).triggerExport());
    await page.waitForFunction(
      () => (window as any).testResults?.testComplete === true,
      { timeout: 120000 }
    );

    results = await page.evaluate(() => (window as any).testResults);
    console.log('Step 3 results:', JSON.stringify(results, null, 2));

    // Verify success
    expect(results.conversionSuccess).toBe(true);
    expect(results.conversionError).toBeNull();
    expect(results.pdfSize).toBeGreaterThan(0);

    console.log(`Step 3 passed: Conversion succeeded with ${results.pdfSize} bytes`);
    console.log('');
    console.log('=== Angular CLI Assets Configuration Test Complete ===');
    console.log('The documented angular.json assets configuration works correctly!');
  });
});

/**
 * Test that verifies the copy-webpack-plugin approach from the error message works.
 * This is the pure Webpack 5 way of copying assets, as an alternative to Angular's assets config.
 */
test.describe('Webpack 5 copy-webpack-plugin Approach', () => {
  let serverProcess: ChildProcess | null = null;
  const WEBPACK_TEST_PORT = 4297;
  const packageJsonPath = join(PROJECT_DIR, 'package.json');
  let originalAngularJson: string;
  let originalWebpackConfig: string;
  let originalPackageJson: string;

  test.beforeAll(async () => {
    // Ensure plugin is built
    if (!existsSync(join(PLUGIN_DIR, 'dist', 'index.mjs'))) {
      console.log('Building plugin...');
      execSync('pnpm run build', { cwd: PLUGIN_DIR, stdio: 'inherit' });
    }

    // Create project if it doesn't exist
    if (!existsSync(PROJECT_DIR)) {
      console.log('Creating Angular test project...');
      execSync('bash scripts/create-angular-cesdk-test-project.sh', {
        cwd: PLUGIN_DIR,
        stdio: 'inherit'
      });
    }

    // Use shared originals or read from file
    const fs = await import('fs/promises');
    if (ORIGINAL_ANGULAR_JSON) {
      originalAngularJson = ORIGINAL_ANGULAR_JSON;
      // Restore to original state in case a previous test left it modified
      await fs.writeFile(ANGULAR_JSON_PATH, originalAngularJson);
    } else {
      originalAngularJson = await fs.readFile(ANGULAR_JSON_PATH, 'utf-8');
    }
    if (ORIGINAL_WEBPACK_CONFIG) {
      originalWebpackConfig = ORIGINAL_WEBPACK_CONFIG;
      await fs.writeFile(WEBPACK_CONFIG_PATH, originalWebpackConfig);
    } else {
      originalWebpackConfig = await fs.readFile(WEBPACK_CONFIG_PATH, 'utf-8');
    }
    originalPackageJson = await fs.readFile(packageJsonPath, 'utf-8');
  });

  test.afterAll(async () => {
    // Restore original files
    const fs = await import('fs/promises');
    if (originalAngularJson) {
      await fs.writeFile(ANGULAR_JSON_PATH, originalAngularJson);
    }
    if (originalWebpackConfig) {
      await fs.writeFile(WEBPACK_CONFIG_PATH, originalWebpackConfig);
    }
    if (originalPackageJson) {
      await fs.writeFile(packageJsonPath, originalPackageJson);
    }

    // Kill server if running
    if (serverProcess) {
      console.log('Stopping webpack test server...');
      serverProcess.kill('SIGTERM');
      serverProcess = null;
    }
  });

  test('should work with copy-webpack-plugin instead of angular.json assets', async ({ page }) => {
    const fs = await import('fs/promises');

    // ============================================
    // STEP 1: Install copy-webpack-plugin
    // ============================================
    console.log('Step 1: Installing copy-webpack-plugin...');

    // Add copy-webpack-plugin to devDependencies
    const packageJson = JSON.parse(originalPackageJson);
    packageJson.devDependencies['copy-webpack-plugin'] = '^12.0.0';
    await fs.writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2));

    // Install the new dependency
    execSync('npm install', { cwd: PROJECT_DIR, stdio: 'inherit', timeout: 120000 });

    // Recreate the plugin symlink (npm install may have removed it)
    const pluginSymlinkPath = join(PROJECT_DIR, 'node_modules', '@imgly', 'plugin-print-ready-pdfs-web');
    const imglyDir = join(PROJECT_DIR, 'node_modules', '@imgly');
    if (!existsSync(imglyDir)) {
      await fs.mkdir(imglyDir, { recursive: true });
    }
    try {
      await fs.unlink(pluginSymlinkPath);
    } catch {
      // Symlink didn't exist
    }
    await fs.symlink(PLUGIN_DIR, pluginSymlinkPath);
    console.log('Recreated plugin symlink');

    // ============================================
    // STEP 2: Configure webpack.config.js with CopyPlugin
    // ============================================
    console.log('Step 2: Configuring webpack.config.js with CopyPlugin...');

    // This is the EXACT pattern from our error message that real users would use:
    // new CopyPlugin({ patterns: [{ from: "node_modules/@imgly/plugin-print-ready-pdfs-web/dist/*.{js,wasm,icc}", to: "assets/[name][ext]" }] })
    const webpackConfigWithCopyPlugin = `// Custom Webpack 5 configuration with copy-webpack-plugin
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  resolve: {
    fallback: {
      fs: false,
      path: false,
      crypto: false
    }
  },
  module: {
    rules: [
      {
        test: /\\.wasm$/,
        type: 'asset/resource'
      }
    ]
  },
  externals: {
    'fs': 'commonjs fs',
    'path': 'commonjs path'
  },
  plugins: [
    // This is the EXACT pattern from the error message - what real users would copy-paste
    new CopyPlugin({
      patterns: [
        {
          from: 'node_modules/@imgly/plugin-print-ready-pdfs-web/dist/*.{js,wasm,icc}',
          to: 'assets/[name][ext]'
        }
      ]
    })
  ]
};
`;
    await fs.writeFile(WEBPACK_CONFIG_PATH, webpackConfigWithCopyPlugin);

    // ============================================
    // STEP 3: Remove Angular assets config (use only webpack plugin)
    // ============================================
    console.log('Step 3: Removing angular.json assets config (using only CopyPlugin)...');

    const angularJson = JSON.parse(originalAngularJson);
    const buildOptions = angularJson.projects['webpack5-angular-cesdk-project'].architect.build.options;

    // Remove ALL plugin asset configurations from angular.json
    buildOptions.assets = buildOptions.assets.filter((asset: any) => {
      if (typeof asset === 'string') return true;
      return !asset.input?.includes('plugin-print-ready-pdfs-web');
    });

    await fs.writeFile(ANGULAR_JSON_PATH, JSON.stringify(angularJson, null, 2));

    // ============================================
    // STEP 4: Build and verify assets are copied by CopyPlugin
    // ============================================
    console.log('Step 4: Building Angular project with CopyPlugin...');
    execSync('npm run build', { cwd: PROJECT_DIR, stdio: 'inherit', timeout: 300000 });

    // Verify assets were copied by CopyPlugin to /assets/
    const distAssetsDir = join(PROJECT_DIR, 'dist', 'webpack5-angular-cesdk-project', 'assets');
    const expectedFiles = ['gs.js', 'gs.wasm', 'ISOcoated_v2_eci.icc', 'GRACoL2013_CRPC6.icc', 'sRGB_IEC61966-2-1.icc'];
    for (const file of expectedFiles) {
      const filePath = join(distAssetsDir, file);
      if (!existsSync(filePath)) {
        throw new Error(`CopyPlugin did not copy ${file} to dist/assets/`);
      }
    }
    console.log('Assets copied successfully by copy-webpack-plugin to /assets/');

    // ============================================
    // STEP 5: Start server and test conversion
    // ============================================
    console.log('Step 5: Starting server and testing conversion...');

    serverProcess = spawn('npx', ['http-server', 'dist/webpack5-angular-cesdk-project', '-p', String(WEBPACK_TEST_PORT), '--cors', '-c-1'], {
      cwd: PROJECT_DIR,
      stdio: 'pipe',
      detached: false
    });

    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Server startup timeout')), 30000);
      serverProcess!.stdout?.on('data', (data) => {
        const output = data.toString();
        console.log('[Webpack Test Server]', output);
        if (output.includes('Available on') || output.includes('Serving')) {
          clearTimeout(timeout);
          setTimeout(resolve, 1000);
        }
      });
      serverProcess!.stderr?.on('data', (data) => console.error('[Webpack Test Server Error]', data.toString()));
      serverProcess!.on('error', (error) => { clearTimeout(timeout); reject(error); });
    });

    // Navigate with a custom query param to use /assets/ path (where CopyPlugin put the files)
    // We need to update the app to support this, or use a different approach
    await page.goto(`http://localhost:${WEBPACK_TEST_PORT}/?assetPath=/assets/`, { timeout: 60000 });
    await page.waitForLoadState('networkidle');

    // Wait for CE.SDK
    await page.waitForFunction(
      () => (window as any).testResults?.cesdkReady === true,
      { timeout: 120000 }
    );

    // Trigger export
    await page.evaluate(() => (window as any).triggerExport());
    await page.waitForFunction(
      () => (window as any).testResults?.testComplete === true,
      { timeout: 120000 }
    );

    const results = await page.evaluate(() => (window as any).testResults);
    console.log('Test results:', JSON.stringify(results, null, 2));

    // Verify success
    expect(results.conversionSuccess).toBe(true);
    expect(results.conversionError).toBeNull();
    expect(results.pdfSize).toBeGreaterThan(0);

    console.log(`Conversion succeeded with ${results.pdfSize} bytes`);
    console.log('');
    console.log('=== Webpack 5 copy-webpack-plugin Test Complete ===');
    console.log('The documented copy-webpack-plugin configuration works correctly!');
  });
});
